enable-magisk-update = true
parallel-jobs = 1
remove-rv-integrations-checks = true

[(Original Icon) YT RVX]
app-name = "YouTube"
enabled = true
version = "19.32.36"
patches-source = "anddea/revanced-patches"
patches-version = "dev"
integrations-source = "anddea/revanced-integrations"
integrations-version = "dev"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
build-mode = "module"
arch = "both"
excluded-patches = "'Custom branding icon for YouTube' 'Custom branding name for YouTube'"
included-patches = "'MaterialYou' 'Hide Shorts dimming'"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"

[(Original Icon) YTM RVX]
app-name = "Music"
enabled = false
version = "7.27.52"
patches-source = "anddea/revanced-patches"
patches-version = "dev"
integrations-source = "anddea/revanced-integrations"
integrations-version = "dev"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
build-mode = "module"
arch = "both"
excluded-patches = "'Custom branding icon for YouTube' 'Custom branding name for YouTube'"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"

[(Original Icon) Piko ReVanced]
enabled = false
version = "10.65.2-release.0"
patches-source = "crimera/piko"
patches-version = "dev"
integrations-source = "crimera/revanced-integrations"
integrations-version = "dev"
cli-source = "revanced/revanced-cli"
arch = "both"
build-mode = "apk"
dpi = "120-640dpi"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter"
